### ISSUE TITLE
X-ray and shim consultation

### ISSUE THREAD

**Issue by marcosbravo** [Sam-Martin/aws-xray-lambda-segment-shim#11]
Hi Sam!

I am a Cloud Engineer, and related to the project I am currently working on has arisen the need to use X-Ray.

Currently we have a pool of lambdas that are invoked by SQS events.

A few of these lambdas in turn invoke via SQS the execution of other lambdas.

I was quite disheartened when I started using x-ray because the truth is that although the lambdas could be painted on the service map, the sqs could not.

After several searches I found the solution that you propose, and I have achieved that when a lambda invokes another one via intermediate SQS event it appears correctly in X-Ray.

However, of the pool of lambdas is the smallest number, most simply receive an SQS event that triggers them; I followed the tutorial but what I get are 2 isolated traces, one only traces the execution of the lambda, and the other paints the lambda with a subsegment making the SQS call.

My question is if it is possible, to have in service map the diagram as you present it in the web, that is to say, that first appears the SQS and then linked the lambda.

<img width="670" alt="Captura de pantalla 2021-11-04 a las 9 00 28" src="https://user-images.githubusercontent.com/48148376/140277884-917c5a44-e44a-48fd-b0be-c4ed53d916bd.png">

I don't know if you could help me in any way and guide me in this.

I attach some screenshots with what I have achieved when the SQS event is between a lambda and another; and the obtaining of the 2 isolated calls when it is a direct SQS event that calls the lambda.

<img width="1751" alt="Captura de pantalla 2021-11-03 a las 11 53 57" src="https://user-images.githubusercontent.com/48148376/140278358-07f24e9c-14c4-4f0f-952c-93281d897ee0.png">
<img width="1917" alt="Captura de pantalla 2021-11-03 a las 11 55 32" src="https://user-images.githubusercontent.com/48148376/140278364-04cac49a-81d8-4b88-9863-4bb31f6e32fe.png">
<img width="1916" alt="Captura de pantalla 2021-11-03 a las 11 59 28" src="https://user-images.githubusercontent.com/48148376/140278367-adc6f9a6-1f38-4ddc-a1c4-e066e3de2921.png">
<img width="1916" alt="Captura de pantalla 2021-11-03 a las 11 59 53" src="https://user-images.githubusercontent.com/48148376/140278370-91f12ae9-4b31-4abb-98f2-940656bb8089.png">

**Comment by Sam-Martin** [comment]
Hi @marcosbravo, thanks for raising an issue.
This image here:
![image](https://user-images.githubusercontent.com/803607/140551646-ab71605c-fb65-4e88-ae20-041f0f8ada8c.png)
looks like the optimal outcome to me, as it shows the lambda posting to sqs, and then sqs triggering the lambda.
What's missing here that you're looking for? Do you want it to _just_ show the sqs queue and then the lambda that triggers? Or is it the other images that are the problem? Are they the same functions? I'm not clear on what your setup looks like.

To help, can you:
1. Draw out your infrastructure using https://draw.io/ or similar so it's easier to understand what it actually looks like (multiple diagrams would be helpful if you have multiple data flows!)
2. Draw out your ideal x-ray trace so I know what we're aiming for?

Many thanks!

**Comment by Sam-Martin** [comment]
Closed due to inactivity.
